/*
Wheel of Fortune Game
ICS4U Final Summative
Instructions frame
 */
package wheeloffortune2;


public class Instructions extends javax.swing.JFrame {
    //this frame is invoked after the user presses the instructions button on the GamePlay screen
    GamePlay firstWindow;
    public Instructions(GamePlay f) {
        initComponents();
        //construct it using the GamePlay screen
        firstWindow=f;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        highscoresTextArea = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        howToPlayLabel = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        quitButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        howToTextArea = new javax.swing.JTextArea();

        highscoresTextArea.setEditable(false);
        highscoresTextArea.setBackground(new java.awt.Color(255, 255, 102));
        highscoresTextArea.setColumns(20);
        highscoresTextArea.setRows(5);
        jScrollPane1.setViewportView(highscoresTextArea);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 204));
        jPanel1.setForeground(new java.awt.Color(0, 51, 204));

        howToPlayLabel.setBackground(new java.awt.Color(255, 255, 102));
        howToPlayLabel.setFont(new java.awt.Font("MS UI Gothic", 1, 40)); // NOI18N
        howToPlayLabel.setForeground(new java.awt.Color(255, 255, 102));
        howToPlayLabel.setText(" HOW TO PLAY");
        howToPlayLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 102), 7, true));

        backButton.setBackground(new java.awt.Color(255, 255, 102));
        backButton.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N
        backButton.setForeground(new java.awt.Color(0, 51, 204));
        backButton.setText("BACK");
        backButton.setToolTipText("");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        quitButton.setBackground(new java.awt.Color(255, 255, 102));
        quitButton.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N
        quitButton.setForeground(new java.awt.Color(0, 51, 204));
        quitButton.setText("QUIT");
        quitButton.setToolTipText("");
        quitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitButtonActionPerformed(evt);
            }
        });

        howToTextArea.setEditable(false);
        howToTextArea.setBackground(new java.awt.Color(255, 255, 102));
        howToTextArea.setColumns(20);
        howToTextArea.setForeground(new java.awt.Color(0, 51, 204));
        howToTextArea.setRows(5);
        howToTextArea.setText("-First, press play and spin the wheel. The money the ticker lands on is your 'spin money'.\n\n-You will get this amount for every correct letter you guess, and if you get the phrase correct, \nyou will get this amount multiplied by 3 added onto your total.\n\n-If you land on bankrupcy, your total money will reset to 0, however your 'spin money' will \nbe $500, so you can earn some money back.\n\n- On the board, green squares are where the letters of the phrase are, white squares are for\nspaces, and red squares are just empty spaces. Guess constants for free, but vowels cost\nmoney. Once you think you know what the phrase it, type it out and press guess!\n\n-Repeat the first two steps twice more for a total of 3 spins, and then save your score and\ngo look at the highscores leaderboard!\n");
        jScrollPane2.setViewportView(howToTextArea);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(backButton, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                            .addComponent(quitButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(howToPlayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(143, Short.MAX_VALUE)
                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(quitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(howToPlayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        //if the user wants to return to the 'homescreen' 
        //set this screen's visibilty to false
        this.setVisible(false);
        //create a new gameplay screen and set its visibility to true
        GamePlay main = new GamePlay();
        main.setVisible(true);
        
    }//GEN-LAST:event_backButtonActionPerformed

    private void quitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitButtonActionPerformed
        //if the user wants to quit, close the GUI
        System.exit(0);
    }//GEN-LAST:event_quitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JTextArea highscoresTextArea;
    private javax.swing.JLabel howToPlayLabel;
    private javax.swing.JTextArea howToTextArea;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton quitButton;
    // End of variables declaration//GEN-END:variables
}
