/*
 * Wheel of Fortune Game
 * ICS4U final project
 * Play Frame 4-final screen 
 * June 11th 2025
 */
package wheeloffortune2;
//import statements used through the code

import java.io.*;
import java.io.IOException;
import java.text.DecimalFormat;
import javax.swing.JLabel;

public class PlayFrame4 extends javax.swing.JFrame {
    //declare variables

    GamePlay playFrame;
    HighScores highScoresFrame;
    PlayFrame2 secondFrame;
    private JLabel phraseAnswer;
    private Player player;
    private JLabel correct;

    public PlayFrame4(PlayFrame2 f) {
        secondFrame = f;
        initComponents();
        //new DecimalFormat for money formatting
        DecimalFormat money = new DecimalFormat("$##,###.00");
        phraseAnswer = phraseAnswerLabel;
        correct = correctLabel;
        //get variables from previous frames
        player = secondFrame.getPlayer();
        //set label text
        totalMoneyLabel.setText("Final Score:   " + money.format(player.getHighscore()));

    }

    /**
     * Accessor that returns the label with the answer to the quesiton
     *
     * @return JLabel showing the answer to the question
     */
    public JLabel getPhraseAnswerLabel() {
        return phraseAnswerLabel;
    }

    /**
     * Accessor that returns the label which shows if the guess was correct
     *
     * @return jlabel showing the correctness of the user's answer
     */
    public JLabel getCorrectLabel() {
        return correct;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        playAgainButton = new javax.swing.JButton();
        correctLabel = new javax.swing.JLabel();
        noEditLabel = new javax.swing.JLabel();
        phraseAnswerLabel = new javax.swing.JLabel();
        guessesLeftLabel = new javax.swing.JLabel();
        totalMoneyLabel = new javax.swing.JLabel();
        highscoresButton1 = new javax.swing.JButton();
        quitButton = new javax.swing.JButton();
        saveScoreButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 204));

        playAgainButton.setBackground(new java.awt.Color(255, 255, 102));
        playAgainButton.setFont(new java.awt.Font("MS UI Gothic", 1, 24)); // NOI18N
        playAgainButton.setForeground(new java.awt.Color(0, 51, 204));
        playAgainButton.setText("Homepage");
        playAgainButton.setToolTipText("");
        playAgainButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playAgainButtonActionPerformed(evt);
            }
        });

        correctLabel.setBackground(new java.awt.Color(255, 255, 102));
        correctLabel.setFont(new java.awt.Font("MS UI Gothic", 1, 36)); // NOI18N
        correctLabel.setForeground(new java.awt.Color(255, 255, 102));
        correctLabel.setText("That is correct!");

        noEditLabel.setBackground(new java.awt.Color(255, 255, 102));
        noEditLabel.setFont(new java.awt.Font("MS UI Gothic", 1, 36)); // NOI18N
        noEditLabel.setForeground(new java.awt.Color(255, 255, 102));
        noEditLabel.setText("The phrase was: ");

        phraseAnswerLabel.setBackground(new java.awt.Color(255, 255, 102));
        phraseAnswerLabel.setFont(new java.awt.Font("MS UI Gothic", 1, 36)); // NOI18N
        phraseAnswerLabel.setForeground(new java.awt.Color(255, 255, 102));
        phraseAnswerLabel.setText("......");

        guessesLeftLabel.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N
        guessesLeftLabel.setForeground(new java.awt.Color(255, 255, 255));
        guessesLeftLabel.setText("Spins Left: 0");
        guessesLeftLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5));

        totalMoneyLabel.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N
        totalMoneyLabel.setForeground(new java.awt.Color(255, 255, 255));
        totalMoneyLabel.setText("Final Score: ");
        totalMoneyLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5));

        highscoresButton1.setBackground(new java.awt.Color(255, 255, 102));
        highscoresButton1.setFont(new java.awt.Font("MS UI Gothic", 1, 24)); // NOI18N
        highscoresButton1.setForeground(new java.awt.Color(0, 51, 204));
        highscoresButton1.setText("Go to Highscores");
        highscoresButton1.setToolTipText("");
        highscoresButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                highscoresButton1ActionPerformed(evt);
            }
        });

        quitButton.setBackground(new java.awt.Color(255, 255, 102));
        quitButton.setFont(new java.awt.Font("MS UI Gothic", 1, 24)); // NOI18N
        quitButton.setForeground(new java.awt.Color(0, 51, 204));
        quitButton.setText("Quit");
        quitButton.setToolTipText("");
        quitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitButtonActionPerformed(evt);
            }
        });

        saveScoreButton.setBackground(new java.awt.Color(255, 255, 102));
        saveScoreButton.setFont(new java.awt.Font("MS UI Gothic", 1, 24)); // NOI18N
        saveScoreButton.setForeground(new java.awt.Color(0, 51, 204));
        saveScoreButton.setText("Save Score");
        saveScoreButton.setToolTipText("");
        saveScoreButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveScoreButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(correctLabel)
                        .addGap(18, 18, 18)
                        .addComponent(noEditLabel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(phraseAnswerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(guessesLeftLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(66, 66, 66)
                                .addComponent(totalMoneyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(79, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(highscoresButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(playAgainButton, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(quitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(saveScoreButton, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(280, 280, 280))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(correctLabel)
                    .addComponent(noEditLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(phraseAnswerLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guessesLeftLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalMoneyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addComponent(saveScoreButton)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(playAgainButton)
                    .addComponent(quitButton)
                    .addComponent(highscoresButton1))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void playAgainButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playAgainButtonActionPerformed
        if (playFrame == null) {
            playFrame = new GamePlay();
        }
        playFrame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_playAgainButtonActionPerformed

    private void highscoresButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_highscoresButton1ActionPerformed
        
        if (highScoresFrame == null) {
            //create a new GamePlay screen
            GamePlay play = new GamePlay();
            //create new highscore frame using the gameplay screen
            highScoresFrame = new HighScores(play);
        }
        //set the higshcores frame visible and set this frame invisible
        highScoresFrame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_highscoresButton1ActionPerformed

    private void quitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitButtonActionPerformed
        //quit the GUI
        System.exit(0);
    }//GEN-LAST:event_quitButtonActionPerformed

    private void saveScoreButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveScoreButtonActionPerformed
        //get the Player fromt he second frame
        Player player = secondFrame.getPlayer();
        //get the highscore also from the second frame, as getting it from the player causes some errors
        int highscore = secondFrame.getHighscore();
        //set the highscore as an extre precaution
        player.setHighscore(highscore);
        //write the player name and highscore to the playerList.txt data file
        try (FileWriter fw = new FileWriter("src/wheeloffortune2/playerList.txt", true); BufferedWriter bw = new BufferedWriter(fw); PrintWriter out = new PrintWriter(bw)) {
            
            out.println(player.toString());  // Writes player's data on a new line

        } catch (IOException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_saveScoreButtonActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel correctLabel;
    private javax.swing.JLabel guessesLeftLabel;
    private javax.swing.JButton highscoresButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel noEditLabel;
    private javax.swing.JLabel phraseAnswerLabel;
    private javax.swing.JButton playAgainButton;
    private javax.swing.JButton quitButton;
    private javax.swing.JButton saveScoreButton;
    private javax.swing.JLabel totalMoneyLabel;
    // End of variables declaration//GEN-END:variables
}
