package wheeloffortune2;

import java.awt.Color;
import java.awt.*;
import java.util.ArrayList;
import javax.swing.*;

/**
 *
 * @author annak
 */
public class PlayFrame1 extends javax.swing.JFrame {

    private PlayFrame2 secondFrame;
    GamePlay firstWindow;

    private PlayFrame3 thirdFrame;
    private String username;
    private Player player;
    private ArrayList<Phrase> phrases;
    private Phrase p;
    private SelectionWheel selectionWheel;

    public PlayFrame1(GamePlay f) {
        initComponents();
        firstWindow = f;
        username = firstWindow.getUsername();
        player = firstWindow.getPlayer();
        phrases = firstWindow.getPhrases();

        try {
            ArrayList<String> list = new ArrayList<String>();
            list.add("$600");
            list.add("$500");
            list.add("$550");
            list.add("$600");
            list.add("$650");
            list.add("Bankruptcy");
            list.add("$650");
            list.add("$500");
            list.add("$600");
            list.add("$650");
            list.add("Bankruptcy");
            list.add("$550");
            list.add("$600");
            list.add("$650");
            list.add("Bankruptcy");

            selectionWheel = new SelectionWheel(list);
            selectionWheel.hasBorders(true);

            wheelPanel.setLayout(new java.awt.FlowLayout(FlowLayout.CENTER, 0, 0));
            wheelPanel.add(selectionWheel);

        } catch (Exception e) {
            e.printStackTrace();
        }

        wheelPanel.revalidate();
        wheelPanel.repaint();

    }

    public String getUsername() {
        return username;
    }

    public Player getPlayer() {
        return firstWindow.getPlayer();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        spinsLeftLabel = new javax.swing.JLabel();
        spinsLeftLabel1 = new javax.swing.JLabel();
        guessPhraseButton = new javax.swing.JButton();
        spinMoneyLabel = new javax.swing.JLabel();
        spinButton1 = new javax.swing.JButton();
        wheelPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 204));

        spinsLeftLabel.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N
        spinsLeftLabel.setForeground(new java.awt.Color(255, 255, 255));
        spinsLeftLabel.setText("Spins Left:");

        spinsLeftLabel1.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N
        spinsLeftLabel1.setForeground(new java.awt.Color(255, 255, 255));
        spinsLeftLabel1.setText("Current Earnings:");

        guessPhraseButton.setBackground(new java.awt.Color(255, 255, 102));
        guessPhraseButton.setFont(new java.awt.Font("MS UI Gothic", 1, 21)); // NOI18N
        guessPhraseButton.setForeground(new java.awt.Color(0, 51, 204));
        guessPhraseButton.setText("Next: Guess Phrase");
        guessPhraseButton.setToolTipText("");
        guessPhraseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guessPhraseButtonActionPerformed(evt);
            }
        });

        spinMoneyLabel.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N
        spinMoneyLabel.setForeground(new java.awt.Color(255, 255, 255));
        spinMoneyLabel.setText("Spin Money:");

        spinButton1.setBackground(new java.awt.Color(255, 255, 102));
        spinButton1.setFont(new java.awt.Font("MS UI Gothic", 1, 48)); // NOI18N
        spinButton1.setForeground(new java.awt.Color(0, 51, 204));
        spinButton1.setText("SPIN WHEEL");
        spinButton1.setToolTipText("");
        spinButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spinButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout wheelPanelLayout = new javax.swing.GroupLayout(wheelPanel);
        wheelPanel.setLayout(wheelPanelLayout);
        wheelPanelLayout.setHorizontalGroup(
            wheelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 451, Short.MAX_VALUE)
        );
        wheelPanelLayout.setVerticalGroup(
            wheelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 292, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(wheelPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(spinsLeftLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(spinsLeftLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(33, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 31, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(spinButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(70, 70, 70))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(spinMoneyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(guessPhraseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(spinsLeftLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spinsLeftLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addComponent(spinButton1)
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(spinMoneyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(guessPhraseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(wheelPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(111, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void guessPhraseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guessPhraseButtonActionPerformed

        ArrayList<Phrase> copy = (ArrayList<Phrase>) phrases.clone();
        int rNum = (int) (Math.random() * copy.size()) + 0;
        p = copy.get(rNum);
        copy.remove(p);

        if (secondFrame == null) {
            secondFrame = new PlayFrame2(this);
        }
        secondFrame.setVisible(true);
        this.setVisible(false);

        String answer;
        String answerSplit[];
        int count;
        int totalCount = 0;

        answer = p.getAnswer();
        answerSplit = answer.split(" ");

        TextField letters[] = secondFrame.getLetters();

        for (int i = 0; i < answerSplit.length; i++) {
            count = answerSplit[i].length();
            for (int j = totalCount; j < count + totalCount; j++) {
                letters[j].setBackground(Color.green);
            }

            if (i < answerSplit.length - 1) {
                letters[totalCount + count].setBackground(Color.white);
            }

            totalCount += count + 1;

        }

        JTextField clue = secondFrame.getClueField();
        clue.setText(p.getQuestion());
    }//GEN-LAST:event_guessPhraseButtonActionPerformed

    public Phrase getPhrase() {
        return p;
    }

    private void spinButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spinButton1ActionPerformed
        spinButton1.setEnabled(false); // disable spin button while spinning
        selectionWheel.setRotationAngle(Math.random() * 360);
        

        try {
            selectionWheel.spinStartAsync(300, -1, -50);

            Timer tickTimer = new Timer(33, e -> selectionWheel.repaintTick());
            tickTimer.start();

            new Thread(() -> {
                while (selectionWheel.isSpinning()) {
                    try {
                        Thread.sleep(10);
                    } catch (InterruptedException ignored) {
                    }
                }

                tickTimer.stop();

                SwingUtilities.invokeLater(() -> spinButton1.setEnabled(true));
            }).start();

        } catch (Exception e) {
            e.printStackTrace();
            return;
        }

        String result = selectionWheel.getSelectedString();
        System.out.println("Landed On: " + result);

    }//GEN-LAST:event_spinButton1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton guessPhraseButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton spinButton1;
    private javax.swing.JLabel spinMoneyLabel;
    private javax.swing.JLabel spinsLeftLabel;
    private javax.swing.JLabel spinsLeftLabel1;
    private javax.swing.JPanel wheelPanel;
    // End of variables declaration//GEN-END:variables
}
