/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package wheeloffortune2;

import javax.swing.*;

public class PlayFrame3 extends javax.swing.JFrame {
    PlayFrame2 secondFrame;
    private JLabel phraseAnswer;
    PlayFrame1 firstFrame;
    
    public PlayFrame3(PlayFrame2 f) {
        initComponents();
        secondFrame=f;
        phraseAnswer = phraseAnswerLabel;
        if(!secondFrame.getStatus()){
            correctLabel.setText("That's incorrect.");
        }
    }

    public JLabel getPhraseAnswerLabel() {
        return phraseAnswerLabel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        spinButton1 = new javax.swing.JButton();
        correctLabel = new javax.swing.JLabel();
        noEditLabel = new javax.swing.JLabel();
        phraseAnswerLabel = new javax.swing.JLabel();
        guessesLeftLabel = new javax.swing.JLabel();
        totalMoneyLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 204));

        spinButton1.setBackground(new java.awt.Color(255, 255, 102));
        spinButton1.setFont(new java.awt.Font("MS UI Gothic", 1, 24)); // NOI18N
        spinButton1.setForeground(new java.awt.Color(0, 51, 204));
        spinButton1.setText("Spin again");
        spinButton1.setToolTipText("");
        spinButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spinButton1ActionPerformed(evt);
            }
        });

        correctLabel.setBackground(new java.awt.Color(255, 255, 102));
        correctLabel.setFont(new java.awt.Font("MS UI Gothic", 1, 36)); // NOI18N
        correctLabel.setForeground(new java.awt.Color(255, 255, 102));
        correctLabel.setText("That is correct!");

        noEditLabel.setBackground(new java.awt.Color(255, 255, 102));
        noEditLabel.setFont(new java.awt.Font("MS UI Gothic", 1, 36)); // NOI18N
        noEditLabel.setForeground(new java.awt.Color(255, 255, 102));
        noEditLabel.setText("The phrase was: ");

        phraseAnswerLabel.setBackground(new java.awt.Color(255, 255, 102));
        phraseAnswerLabel.setFont(new java.awt.Font("MS UI Gothic", 1, 36)); // NOI18N
        phraseAnswerLabel.setForeground(new java.awt.Color(255, 255, 102));
        phraseAnswerLabel.setText("......");

        guessesLeftLabel.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N
        guessesLeftLabel.setForeground(new java.awt.Color(255, 255, 255));
        guessesLeftLabel.setText("Spins Left:");
        guessesLeftLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5));

        totalMoneyLabel.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N
        totalMoneyLabel.setForeground(new java.awt.Color(255, 255, 255));
        totalMoneyLabel.setText("Total Money:");
        totalMoneyLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(correctLabel)
                        .addGap(18, 18, 18)
                        .addComponent(noEditLabel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(phraseAnswerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(123, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(guessesLeftLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(totalMoneyLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                .addGap(37, 37, 37)
                .addComponent(spinButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(correctLabel)
                    .addComponent(noEditLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(phraseAnswerLabel)
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spinButton1)
                    .addComponent(guessesLeftLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalMoneyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void spinButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spinButton1ActionPerformed
        if (firstFrame == null) {
            GamePlay play=new GamePlay();
            firstFrame = new PlayFrame1(play);
        }
        firstFrame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_spinButton1ActionPerformed

   
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel correctLabel;
    private javax.swing.JLabel guessesLeftLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel noEditLabel;
    private javax.swing.JLabel phraseAnswerLabel;
    private javax.swing.JButton spinButton1;
    private javax.swing.JLabel totalMoneyLabel;
    // End of variables declaration//GEN-END:variables
}
