/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package wheeloffortune2;
import java.io.FileWriter;
import java.io.IOException;
public class PlayFrame4 extends javax.swing.JFrame {

        PlayFrame2 secondFrame;
        
        
    public PlayFrame4(PlayFrame2 f) {
        secondFrame=f;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        playAgainButton = new javax.swing.JButton();
        correctLabel = new javax.swing.JLabel();
        noEditLabel = new javax.swing.JLabel();
        phraseAnswerLabel = new javax.swing.JLabel();
        guessesLeftLabel = new javax.swing.JLabel();
        totalMoneyLabel = new javax.swing.JLabel();
        highscoresButton1 = new javax.swing.JButton();
        quitButton = new javax.swing.JButton();
        saveScoreButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 204));

        playAgainButton.setBackground(new java.awt.Color(255, 255, 102));
        playAgainButton.setFont(new java.awt.Font("MS UI Gothic", 1, 24)); // NOI18N
        playAgainButton.setForeground(new java.awt.Color(0, 51, 204));
        playAgainButton.setText("Homepage");
        playAgainButton.setToolTipText("");
        playAgainButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playAgainButtonActionPerformed(evt);
            }
        });

        correctLabel.setBackground(new java.awt.Color(255, 255, 102));
        correctLabel.setFont(new java.awt.Font("MS UI Gothic", 1, 36)); // NOI18N
        correctLabel.setForeground(new java.awt.Color(255, 255, 102));
        correctLabel.setText("That is correct!");

        noEditLabel.setBackground(new java.awt.Color(255, 255, 102));
        noEditLabel.setFont(new java.awt.Font("MS UI Gothic", 1, 36)); // NOI18N
        noEditLabel.setForeground(new java.awt.Color(255, 255, 102));
        noEditLabel.setText("The phrase was: ");

        phraseAnswerLabel.setBackground(new java.awt.Color(255, 255, 102));
        phraseAnswerLabel.setFont(new java.awt.Font("MS UI Gothic", 1, 36)); // NOI18N
        phraseAnswerLabel.setForeground(new java.awt.Color(255, 255, 102));
        phraseAnswerLabel.setText("......");

        guessesLeftLabel.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N
        guessesLeftLabel.setForeground(new java.awt.Color(255, 255, 255));
        guessesLeftLabel.setText("Spins Left: 0");
        guessesLeftLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5));

        totalMoneyLabel.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N
        totalMoneyLabel.setForeground(new java.awt.Color(255, 255, 255));
        totalMoneyLabel.setText("Total Money:");
        totalMoneyLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5));

        highscoresButton1.setBackground(new java.awt.Color(255, 255, 102));
        highscoresButton1.setFont(new java.awt.Font("MS UI Gothic", 1, 24)); // NOI18N
        highscoresButton1.setForeground(new java.awt.Color(0, 51, 204));
        highscoresButton1.setText("Go to Highscores");
        highscoresButton1.setToolTipText("");
        highscoresButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                highscoresButton1ActionPerformed(evt);
            }
        });

        quitButton.setBackground(new java.awt.Color(255, 255, 102));
        quitButton.setFont(new java.awt.Font("MS UI Gothic", 1, 24)); // NOI18N
        quitButton.setForeground(new java.awt.Color(0, 51, 204));
        quitButton.setText("Quit");
        quitButton.setToolTipText("");
        quitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitButtonActionPerformed(evt);
            }
        });

        saveScoreButton.setBackground(new java.awt.Color(255, 255, 102));
        saveScoreButton.setFont(new java.awt.Font("MS UI Gothic", 1, 24)); // NOI18N
        saveScoreButton.setForeground(new java.awt.Color(0, 51, 204));
        saveScoreButton.setText("Save Score");
        saveScoreButton.setToolTipText("");
        saveScoreButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveScoreButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(correctLabel)
                        .addGap(18, 18, 18)
                        .addComponent(noEditLabel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(phraseAnswerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(guessesLeftLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(66, 66, 66)
                                .addComponent(totalMoneyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(79, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(highscoresButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(playAgainButton, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(quitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(saveScoreButton, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(280, 280, 280))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(correctLabel)
                    .addComponent(noEditLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(phraseAnswerLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guessesLeftLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalMoneyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addComponent(saveScoreButton)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(playAgainButton)
                    .addComponent(quitButton)
                    .addComponent(highscoresButton1))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void playAgainButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playAgainButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_playAgainButtonActionPerformed

    private void highscoresButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_highscoresButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_highscoresButton1ActionPerformed

    private void quitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quitButtonActionPerformed

    private void saveScoreButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveScoreButtonActionPerformed
        Player player=secondFrame.getPlayer();
        int highscore=secondFrame.getHighscore();
        player.setHighscore(highscore);
        //test later
        try (FileWriter fw = new FileWriter("src/wheeloffortune2/playerList", true)) {
            fw.write("\n"+player.toString());
        } catch (IOException e) {
            e.printStackTrace();
        
    }

    }//GEN-LAST:event_saveScoreButtonActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel correctLabel;
    private javax.swing.JLabel guessesLeftLabel;
    private javax.swing.JButton highscoresButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel noEditLabel;
    private javax.swing.JLabel phraseAnswerLabel;
    private javax.swing.JButton playAgainButton;
    private javax.swing.JButton quitButton;
    private javax.swing.JButton saveScoreButton;
    private javax.swing.JLabel totalMoneyLabel;
    // End of variables declaration//GEN-END:variables
}
