/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package wheeloffortune2;

import java.awt.TextField;
import javax.swing.*;

/**
 *
 * @author annak
 */
public class PlayFrame2 extends javax.swing.JFrame {

    PlayFrame1 firstFrame;
    private PlayFrame3 thirdFrame;
    private PlayFrame4 fourthFrame;
    private TextField letters[];
    private int highscore;
    private Player player;
    private JTextField clue;
    private Phrase p;
    private String answer;

    public TextField[] getLetters() {
        return letters;
    }

    public int getHighscore() {
        return highscore;
    }

    public Player getPlayer() {
        return player;
    }

    public PlayFrame2(PlayFrame1 f) {
        initComponents();
        firstFrame = f;
        letters = new TextField[]{letter0, letter1, letter2, letter3, letter4, letter5, letter6, letter7,
            letter8, letter9, letter10, letter11, letter12, letter13, letter14, letter15, letter16, letter17,
            letter18, letter19, letter20, letter21, letter22, letter23, letter24, letter25};
        clue = clueField;
        highscore=Integer.parseInt("100");
        player=firstFrame.getPlayer();
        p = firstFrame.getPhrase();
        answer = p.getAnswer();
    }

    public JTextField getClueField() {
        return clueField;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        totalMoneyLabel = new javax.swing.JLabel();
        guessVowelButton = new javax.swing.JButton();
        guessesLeftLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        letter0 = new java.awt.TextField();
        letter1 = new java.awt.TextField();
        letter2 = new java.awt.TextField();
        letter3 = new java.awt.TextField();
        letter4 = new java.awt.TextField();
        letter5 = new java.awt.TextField();
        letter6 = new java.awt.TextField();
        letter7 = new java.awt.TextField();
        letter8 = new java.awt.TextField();
        letter9 = new java.awt.TextField();
        letter10 = new java.awt.TextField();
        letter11 = new java.awt.TextField();
        letter12 = new java.awt.TextField();
        letter13 = new java.awt.TextField();
        letter14 = new java.awt.TextField();
        letter15 = new java.awt.TextField();
        letter16 = new java.awt.TextField();
        letter17 = new java.awt.TextField();
        letter18 = new java.awt.TextField();
        letter19 = new java.awt.TextField();
        letter20 = new java.awt.TextField();
        letter21 = new java.awt.TextField();
        letter22 = new java.awt.TextField();
        letter23 = new java.awt.TextField();
        letter24 = new java.awt.TextField();
        letter25 = new java.awt.TextField();
        nameLabel = new javax.swing.JLabel();
        vowelField = new javax.swing.JTextField();
        consLabel = new javax.swing.JLabel();
        consField1 = new javax.swing.JTextField();
        guessConsonantButton = new javax.swing.JButton();
        hintButton = new javax.swing.JButton();
        hintTextField = new javax.swing.JTextField();
        guessPhraseLabel = new javax.swing.JLabel();
        phraseTextField = new javax.swing.JTextField();
        guessPhraseButton = new javax.swing.JButton();
        noEditHintLabel = new javax.swing.JLabel();
        hintLabel = new javax.swing.JLabel();
        clueField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 204));

        totalMoneyLabel.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N
        totalMoneyLabel.setForeground(new java.awt.Color(255, 255, 255));
        totalMoneyLabel.setText("Total Money:");
        totalMoneyLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5));

        guessVowelButton.setBackground(new java.awt.Color(255, 255, 102));
        guessVowelButton.setFont(new java.awt.Font("MS UI Gothic", 1, 21)); // NOI18N
        guessVowelButton.setForeground(new java.awt.Color(0, 51, 204));
        guessVowelButton.setText("Guess ($300)");
        guessVowelButton.setToolTipText("");
        guessVowelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guessVowelButtonActionPerformed(evt);
            }
        });

        guessesLeftLabel.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N
        guessesLeftLabel.setForeground(new java.awt.Color(255, 255, 255));
        guessesLeftLabel.setText("Guesses Left:");
        guessesLeftLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5));

        letter0.setBackground(new java.awt.Color(255, 0, 0));
        letter0.setEditable(false);
        letter0.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        letter0.setForeground(new java.awt.Color(255, 255, 255));
        letter0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letter0ActionPerformed(evt);
            }
        });

        letter1.setBackground(new java.awt.Color(255, 0, 0));
        letter1.setEditable(false);
        letter1.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        letter1.setForeground(new java.awt.Color(255, 255, 255));

        letter2.setBackground(new java.awt.Color(255, 0, 0));
        letter2.setEditable(false);
        letter2.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        letter2.setForeground(new java.awt.Color(255, 255, 255));

        letter3.setBackground(new java.awt.Color(255, 0, 0));
        letter3.setEditable(false);
        letter3.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        letter3.setForeground(new java.awt.Color(255, 255, 255));

        letter4.setBackground(new java.awt.Color(255, 0, 0));
        letter4.setEditable(false);
        letter4.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        letter4.setForeground(new java.awt.Color(255, 255, 255));

        letter5.setBackground(new java.awt.Color(255, 0, 0));
        letter5.setEditable(false);
        letter5.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        letter5.setForeground(new java.awt.Color(255, 255, 255));

        letter6.setBackground(new java.awt.Color(255, 0, 0));
        letter6.setEditable(false);
        letter6.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        letter6.setForeground(new java.awt.Color(255, 255, 255));

        letter7.setBackground(new java.awt.Color(255, 0, 0));
        letter7.setEditable(false);
        letter7.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        letter7.setForeground(new java.awt.Color(255, 255, 255));

        letter8.setBackground(new java.awt.Color(255, 0, 0));
        letter8.setEditable(false);
        letter8.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        letter8.setForeground(new java.awt.Color(255, 255, 255));

        letter9.setBackground(new java.awt.Color(255, 0, 0));
        letter9.setEditable(false);
        letter9.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        letter9.setForeground(new java.awt.Color(255, 255, 255));

        letter10.setBackground(new java.awt.Color(255, 0, 0));
        letter10.setEditable(false);
        letter10.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        letter10.setForeground(new java.awt.Color(255, 255, 255));

        letter11.setBackground(new java.awt.Color(255, 0, 0));
        letter11.setEditable(false);
        letter11.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        letter11.setForeground(new java.awt.Color(255, 255, 255));

        letter12.setBackground(new java.awt.Color(255, 0, 0));
        letter12.setEditable(false);
        letter12.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        letter12.setForeground(new java.awt.Color(255, 255, 255));

        letter13.setBackground(new java.awt.Color(255, 0, 0));
        letter13.setEditable(false);
        letter13.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        letter13.setForeground(new java.awt.Color(255, 255, 255));

        letter14.setBackground(new java.awt.Color(255, 0, 0));
        letter14.setEditable(false);
        letter14.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        letter14.setForeground(new java.awt.Color(255, 255, 255));

        letter15.setBackground(new java.awt.Color(255, 0, 0));
        letter15.setEditable(false);
        letter15.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        letter15.setForeground(new java.awt.Color(255, 255, 255));

        letter16.setBackground(new java.awt.Color(255, 0, 0));
        letter16.setEditable(false);
        letter16.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        letter16.setForeground(new java.awt.Color(255, 255, 255));

        letter17.setBackground(new java.awt.Color(255, 0, 0));
        letter17.setEditable(false);
        letter17.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        letter17.setForeground(new java.awt.Color(255, 255, 255));

        letter18.setBackground(new java.awt.Color(255, 0, 0));
        letter18.setEditable(false);
        letter18.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        letter18.setForeground(new java.awt.Color(255, 255, 255));

        letter19.setBackground(new java.awt.Color(255, 0, 0));
        letter19.setEditable(false);
        letter19.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        letter19.setForeground(new java.awt.Color(255, 255, 255));

        letter20.setBackground(new java.awt.Color(255, 0, 0));
        letter20.setEditable(false);
        letter20.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        letter20.setForeground(new java.awt.Color(255, 255, 255));

        letter21.setBackground(new java.awt.Color(255, 0, 0));
        letter21.setEditable(false);
        letter21.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        letter21.setForeground(new java.awt.Color(255, 255, 255));

        letter22.setBackground(new java.awt.Color(255, 0, 0));
        letter22.setEditable(false);
        letter22.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        letter22.setForeground(new java.awt.Color(255, 255, 255));

        letter23.setBackground(new java.awt.Color(255, 0, 0));
        letter23.setEditable(false);
        letter23.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        letter23.setForeground(new java.awt.Color(255, 255, 255));

        letter24.setBackground(new java.awt.Color(255, 0, 0));
        letter24.setEditable(false);
        letter24.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        letter24.setForeground(new java.awt.Color(255, 255, 255));

        letter25.setBackground(new java.awt.Color(255, 0, 0));
        letter25.setEditable(false);
        letter25.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        letter25.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(letter0, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(letter1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(letter2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(letter3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(letter4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(letter5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(letter6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(letter7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(letter8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(letter9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(letter10, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(letter11, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(letter12, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(letter13, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(letter14, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(letter15, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(letter16, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(letter17, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(letter18, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(letter19, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(letter20, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(letter21, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(letter22, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(letter23, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(letter24, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(letter25, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(letter12, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letter11, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letter10, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letter9, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letter8, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letter7, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letter6, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letter5, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letter4, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letter3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letter2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letter1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letter0, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(letter13, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letter14, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letter15, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letter16, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letter17, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letter18, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letter19, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letter20, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letter21, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letter22, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letter23, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letter24, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letter25, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        nameLabel.setBackground(new java.awt.Color(255, 255, 102));
        nameLabel.setFont(new java.awt.Font("MS UI Gothic", 1, 24)); // NOI18N
        nameLabel.setForeground(new java.awt.Color(255, 255, 102));
        nameLabel.setText("Guess Vowel:   ");

        vowelField.setBackground(new java.awt.Color(255, 255, 105));
        vowelField.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N
        vowelField.setForeground(new java.awt.Color(0, 51, 204));
        vowelField.setToolTipText("");

        consLabel.setBackground(new java.awt.Color(255, 255, 102));
        consLabel.setFont(new java.awt.Font("MS UI Gothic", 1, 24)); // NOI18N
        consLabel.setForeground(new java.awt.Color(255, 255, 102));
        consLabel.setText("Guess Consonant: ");

        consField1.setBackground(new java.awt.Color(255, 255, 105));
        consField1.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N
        consField1.setForeground(new java.awt.Color(0, 51, 204));
        consField1.setToolTipText("");

        guessConsonantButton.setBackground(new java.awt.Color(255, 255, 102));
        guessConsonantButton.setFont(new java.awt.Font("MS UI Gothic", 1, 21)); // NOI18N
        guessConsonantButton.setForeground(new java.awt.Color(0, 51, 204));
        guessConsonantButton.setText("Guess");
        guessConsonantButton.setToolTipText("");
        guessConsonantButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guessConsonantButtonActionPerformed(evt);
            }
        });

        hintButton.setBackground(new java.awt.Color(255, 255, 102));
        hintButton.setFont(new java.awt.Font("MS UI Gothic", 1, 21)); // NOI18N
        hintButton.setForeground(new java.awt.Color(0, 51, 204));
        hintButton.setText("Get Hint ($500)");
        hintButton.setToolTipText("");
        hintButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hintButtonActionPerformed(evt);
            }
        });

        hintTextField.setEditable(false);
        hintTextField.setBackground(new java.awt.Color(0, 51, 204));
        hintTextField.setFont(new java.awt.Font("MS UI Gothic", 1, 14)); // NOI18N
        hintTextField.setForeground(new java.awt.Color(255, 255, 102));
        hintTextField.setToolTipText("");
        hintTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hintTextFieldActionPerformed(evt);
            }
        });

        guessPhraseLabel.setBackground(new java.awt.Color(255, 255, 102));
        guessPhraseLabel.setFont(new java.awt.Font("MS UI Gothic", 1, 24)); // NOI18N
        guessPhraseLabel.setForeground(new java.awt.Color(255, 255, 102));
        guessPhraseLabel.setText("Guess Phrase: ");

        phraseTextField.setBackground(new java.awt.Color(255, 255, 105));
        phraseTextField.setFont(new java.awt.Font("MS UI Gothic", 1, 14)); // NOI18N
        phraseTextField.setForeground(new java.awt.Color(0, 51, 204));
        phraseTextField.setToolTipText("");

        guessPhraseButton.setBackground(new java.awt.Color(255, 255, 102));
        guessPhraseButton.setFont(new java.awt.Font("MS UI Gothic", 1, 21)); // NOI18N
        guessPhraseButton.setForeground(new java.awt.Color(0, 51, 204));
        guessPhraseButton.setText("Guess Phrase");
        guessPhraseButton.setToolTipText("");
        guessPhraseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guessPhraseButtonActionPerformed(evt);
            }
        });

        noEditHintLabel.setBackground(new java.awt.Color(255, 255, 255));
        noEditHintLabel.setFont(new java.awt.Font("MS UI Gothic", 1, 36)); // NOI18N
        noEditHintLabel.setForeground(new java.awt.Color(255, 255, 255));
        noEditHintLabel.setText("CLUE:");

        hintLabel.setBackground(new java.awt.Color(255, 255, 255));
        hintLabel.setFont(new java.awt.Font("MS UI Gothic", 1, 24)); // NOI18N
        hintLabel.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(guessVowelButton)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(nameLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(vowelField, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(guessConsonantButton, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(consLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(consField1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(guessesLeftLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(hintButton)
                                .addGap(30, 30, 30)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(hintTextField)
                            .addComponent(totalMoneyLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE))
                        .addGap(68, 68, 68))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(guessPhraseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(guessPhraseLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(phraseTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(30, 30, 30))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(noEditHintLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(138, 138, 138)
                                .addComponent(hintLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 633, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(clueField, javax.swing.GroupLayout.PREFERRED_SIZE, 656, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(noEditHintLabel)
                    .addComponent(hintLabel)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(clueField)))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(totalMoneyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(guessesLeftLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nameLabel)
                            .addComponent(vowelField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hintTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hintButton)
                    .addComponent(guessVowelButton))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phraseTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(guessPhraseLabel)
                    .addComponent(consField1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(consLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guessPhraseButton)
                    .addComponent(guessConsonantButton))
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void guessVowelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guessVowelButtonActionPerformed
        boolean letterCheck;
        int vowValue;
        String checkVowel = vowelField.getText();
        char vowel;
        char answerLetter;
        int count = 0;

        if (checkVowel.length() != 1) {
            JOptionPane.showMessageDialog(null, "You can only answer one vowel at a time!", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            vowel = checkVowel.charAt(0);
            letterCheck = Character.isLetter(vowel);

            if (!letterCheck) {
                JOptionPane.showMessageDialog(null, "That is not a letter, let alone a vowel! Try again", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                vowValue = Character.getNumericValue(vowel);
                
                if (vowValue != 10 && vowValue != 14 && vowValue != 18 && vowValue != 24 && vowValue != 30) {
                    JOptionPane.showMessageDialog(null, "That is a consonant not a vowel!", "Error", JOptionPane.ERROR_MESSAGE);
                } else {                   
                   for (int i = 0; i < answer.length(); i++) {
                       answerLetter = answer.charAt(i);
                       if (Character.toLowerCase(answerLetter) == Character.toLowerCase(vowel)) {
                           letters[i].setText(Character.toString((Character.toUpperCase(vowel))));
                           count++;
                       }
                       
                   }
                }
            }

        }

    }//GEN-LAST:event_guessVowelButtonActionPerformed

    private void guessConsonantButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guessConsonantButtonActionPerformed
        boolean letterCheck;
        int consValue;
        String checkConsonant = consField1.getText();
        char consonant;
        char answerLetter;
        int count = 0;

        if (checkConsonant.length() != 1) {
            JOptionPane.showMessageDialog(null, "You can only answer one consonant at a time!", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            consonant = checkConsonant.charAt(0);
            letterCheck = Character.isLetter(consonant);

            if (!letterCheck) {
                JOptionPane.showMessageDialog(null, "That is not a letter, let alone a consonant! Try again", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                consValue = Character.getNumericValue(consonant);
                System.out.println(consValue);
                
                if (consValue == 10 || consValue == 14 || consValue == 18 || consValue == 24 || consValue == 30) {
                    JOptionPane.showMessageDialog(null, "That is a vowel not a consonant!", "Error", JOptionPane.ERROR_MESSAGE);
                } else {
                   for (int i = 0; i < answer.length(); i++) {
                       answerLetter = answer.charAt(i);
                       if (Character.toLowerCase(answerLetter) == Character.toLowerCase(consonant)) {
                           letters[i].setText(Character.toString((Character.toUpperCase(consonant))));
                           count++;
                       }
                       
                   }
                }
            }

        }


    }//GEN-LAST:event_guessConsonantButtonActionPerformed

    private void hintButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hintButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hintButtonActionPerformed

    private void hintTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hintTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hintTextFieldActionPerformed

    private void guessPhraseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guessPhraseButtonActionPerformed
        int numGuesses = 1;//make later
        if (numGuesses != 0) {
            if (thirdFrame == null) {
                thirdFrame = new PlayFrame3(this);
                thirdFrame.setVisible(true);
                this.setVisible(false);
            } else if (numGuesses == 0) {//FIX
                if (fourthFrame == null) {
                    fourthFrame = new PlayFrame4(this);
                    fourthFrame.setVisible(true);
                    this.setVisible(false);
                }
            }
        } 
        
        JLabel phraseAnswer = thirdFrame.getPhraseAnswerLabel();
        phraseAnswer.setText(answer);


    }//GEN-LAST:event_guessPhraseButtonActionPerformed

    private void letter0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letter0ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_letter0ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField clueField;
    private javax.swing.JTextField consField1;
    private javax.swing.JLabel consLabel;
    private javax.swing.JButton guessConsonantButton;
    private javax.swing.JButton guessPhraseButton;
    private javax.swing.JLabel guessPhraseLabel;
    private javax.swing.JButton guessVowelButton;
    private javax.swing.JLabel guessesLeftLabel;
    private javax.swing.JButton hintButton;
    private javax.swing.JLabel hintLabel;
    private javax.swing.JTextField hintTextField;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private java.awt.TextField letter0;
    private java.awt.TextField letter1;
    private java.awt.TextField letter10;
    private java.awt.TextField letter11;
    private java.awt.TextField letter12;
    private java.awt.TextField letter13;
    private java.awt.TextField letter14;
    private java.awt.TextField letter15;
    private java.awt.TextField letter16;
    private java.awt.TextField letter17;
    private java.awt.TextField letter18;
    private java.awt.TextField letter19;
    private java.awt.TextField letter2;
    private java.awt.TextField letter20;
    private java.awt.TextField letter21;
    private java.awt.TextField letter22;
    private java.awt.TextField letter23;
    private java.awt.TextField letter24;
    private java.awt.TextField letter25;
    private java.awt.TextField letter3;
    private java.awt.TextField letter4;
    private java.awt.TextField letter5;
    private java.awt.TextField letter6;
    private java.awt.TextField letter7;
    private java.awt.TextField letter8;
    private java.awt.TextField letter9;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel noEditHintLabel;
    private javax.swing.JTextField phraseTextField;
    private javax.swing.JLabel totalMoneyLabel;
    private javax.swing.JTextField vowelField;
    // End of variables declaration//GEN-END:variables
}
