/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package wheeloffortune2;

import java.awt.Color;
import java.util.ArrayList;
import java.awt.TextField;
import javax.swing.JTextField;

/**
 *
 * @author annak
 */
public class PlayFrame1 extends javax.swing.JFrame {

    private PlayFrame2 secondFrame;
    GamePlay firstWindow;
    private String username;
    private Player player;
    private ArrayList<Phrase> phrases;
    private Phrase p;
    public PlayFrame1(GamePlay f) {
        initComponents();
        firstWindow = f;
        username = firstWindow.getUsername();
        player = firstWindow.getPlayer();
        phrases = firstWindow.getPhrases();
    }
    public String getUsername(){
        return username;
    }
    public Player getPlayer(){
        return player;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        spinsLeftLabel = new javax.swing.JLabel();
        spinsLeftLabel1 = new javax.swing.JLabel();
        guessPhraseButton = new javax.swing.JButton();
        spinMoneyLabel = new javax.swing.JLabel();
        spinButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 204));

        spinsLeftLabel.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N
        spinsLeftLabel.setForeground(new java.awt.Color(255, 255, 255));
        spinsLeftLabel.setText("Spins Left:");
        spinsLeftLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5));

        spinsLeftLabel1.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N
        spinsLeftLabel1.setForeground(new java.awt.Color(255, 255, 255));
        spinsLeftLabel1.setText("Current Earnings:");
        spinsLeftLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5));

        guessPhraseButton.setBackground(new java.awt.Color(255, 255, 102));
        guessPhraseButton.setFont(new java.awt.Font("MS UI Gothic", 1, 21)); // NOI18N
        guessPhraseButton.setForeground(new java.awt.Color(0, 51, 204));
        guessPhraseButton.setText("Next: Guess Phrase");
        guessPhraseButton.setToolTipText("");
        guessPhraseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guessPhraseButtonActionPerformed(evt);
            }
        });

        spinMoneyLabel.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N
        spinMoneyLabel.setForeground(new java.awt.Color(255, 255, 255));
        spinMoneyLabel.setText("Spin Money:");
        spinMoneyLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5));

        spinButton1.setBackground(new java.awt.Color(255, 255, 102));
        spinButton1.setFont(new java.awt.Font("MS UI Gothic", 1, 48)); // NOI18N
        spinButton1.setForeground(new java.awt.Color(0, 51, 204));
        spinButton1.setText("SPIN WHEEL");
        spinButton1.setToolTipText("");
        spinButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spinButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(300, 300, 300)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(spinMoneyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(guessPhraseButton, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(spinsLeftLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(spinsLeftLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(spinButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spinsLeftLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spinsLeftLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(spinButton1)
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(spinMoneyLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(guessPhraseButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(80, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void guessPhraseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guessPhraseButtonActionPerformed
        
        ArrayList<Phrase> copy = (ArrayList<Phrase>) phrases.clone();
        int rNum = (int) (Math.random() * copy.size()) + 0;
        p = copy.get(rNum);
        copy.remove(p);
        
        if (secondFrame == null) {
            secondFrame = new PlayFrame2(this);
        }
        secondFrame.setVisible(true);
        this.setVisible(false);
        
        String answer;
        String answerSplit[];
        int count;
        int totalCount = 0;
       
        
        answer = p.getAnswer();
        answerSplit = answer.split(" ");
        
        TextField letters[] = secondFrame.getLetters();
        
        for (int i = 0; i < answerSplit.length; i++) {
            count = answerSplit[i].length();
            for (int j = totalCount; j < count + totalCount; j++) {
                letters[j].setBackground(Color.green);
            }
            
            if (i < answerSplit.length - 1) {
                letters[totalCount + count].setBackground(Color.white);
            }
            
            totalCount += count + 1;
            
            
        }
        
        System.out.println(p);
        JTextField clue = secondFrame.getClueField();
        clue.setText(p.getQuestion());
    }//GEN-LAST:event_guessPhraseButtonActionPerformed

    public Phrase getPhrase() {
        return p;
    }

    private void spinButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spinButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_spinButton1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton guessPhraseButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton spinButton1;
    private javax.swing.JLabel spinMoneyLabel;
    private javax.swing.JLabel spinsLeftLabel;
    private javax.swing.JLabel spinsLeftLabel1;
    // End of variables declaration//GEN-END:variables
}
